### ISSUE TITLE
Streamlink on Windows opens a cmd window

### ISSUE THREAD

**Issue by mgitkun** [streamlink/streamlink-twitch-gui#336]
### Description

When using Streamlink you're unable to kill a stream that's currently being opened with the close stream button in the pop-up dialogue box. 
### Expected / Actual behavior

Pressing the close stream button closes the dialogue box and ends the connection, preventing the stream from being opened. 
...
Pressing the close stream button closes the dialogue box but does not prevent the stream from being opened.
### Reproduction steps
1. Select Streamlink.exe as the livestreamer executable. 
2. Attempt to open any stream.
3. X out of the dialogue box before the requested stream has been opened.
### Environment details (operating system, etc.)

Windows 7 x64
Livestreamer GUI 0.16.0

**Comment by bastimeyer** [comment]
This is a bug related to Streamlink (or Livestreamer when installed via pip)

See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/331#issuecomment-255597522 and the following comments.

**Comment by bastimeyer** [comment]
Fixed in the [streamproviders](https://github.com/bastimeyer/livestreamer-twitch-gui/compare/master...streamproviders) branch that splits the old livestreamer structure into `streamlink`, `livestreamer` and `livestreamer-standalone` (Windows installer).

Streamlink and Livestreamer will now be launched directly via the python executable (pythonw.exe on Windows) instead of relying on the shebang inside the python scripts which were used previously. This removes the cmd window on Windows while using Streamlink or Livestreamer when installed via pip.

I'm going to close this issue once the branch has been merged into master.

**Comment by stevek123** [comment]
Are there going to be a new release any time soon?

**Comment by bastimeyer** [comment]
I don't have planned anything yet. I want the next release to be the last one with the current name. There's still some work to do, so that the transition can be smooth.

If the cmd window issue with Streamlink on Windows annoys you, just switch back to Livestreamer (which is still working fine thanks to the workarounds in the GUI) or build the application off the master branch and help testing it, so I can be sure that I haven't missed a bug. 😃

**Comment by stevek123** [comment]
I have tried to build it, but I always get the same error:

> Running "webpack:dev" (webpack) task                         events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
  at WriteStream.Socket._writeGeneric (net.js:683:19)
  at WriteStream.Socket._write (net.js:734:8)
  at doWrite (_stream_writable.js:334:12)
  at writeOrBuffer (_stream_writable.js:320:5)
  at WriteStream.Writable.write (_stream_writable.js:247:11)
  at WriteStream.Socket.write (net.js:661:40)
  at Log._write (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\index.js:161:26)
  at Log.wrapper [as _write] (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\node_modules\lodash\index.js:3095:19)
  at Log._writeln (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\index.js:166:8)
  at Log.wrapper [as _writeln] (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\node_modules\lodash\index.js:3095:19)
  at Log.writeln (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\index.js:177:8)
  at Log.wrapper (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt-legacy-log\node_modules\lodash\index.js:3095:19)
  at writeln (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt\lib\grunt\fail.js:30:13)
  at Object.fail.fatal (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt\lib\grunt\fail.js:46:3)
  at process.uncaughtHandler (C:\Users\XYZ\livestreamer-twitch-gui\node_modules\grunt\lib\grunt.js:121:10)
  at emitOne (events.js:96:13)
  at process.emit (events.js:188:7)
  at process._fatalException (bootstrap_node.js:292:26)

**Comment by bastimeyer** [comment]
I don't know what you're doing, but please follow the [contributing guide](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.16.0/CONTRIBUTING.md#developing-and-building) and use the latest stable versions of git, nodejs, npm and bower and make sure that all dependencies are installed correctly.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/releases/latest
