### ISSUE TITLE
Unexpected version check output

### ISSUE THREAD

**Issue by sam-fletcher** [streamlink/streamlink-twitch-gui#380]
I recently downloaded Streamlink to replace Livestreamer, and I can open the GUI and log in to Twitch, but I can't open any streams. In the meantime I'm still using Livestreamer. 

I'm on Windows 10. I'm getting the following error whenever I click on a stream in Streamlink to open it:

Error: Couldn't launch the stream

Unexpected version check output

Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 11, in <module>
from streamlink_cli.main import main
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
from streamlink.stream import StreamProcess
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\__init__.py", line 6, in <module>
from .hls import HLSStream
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 4, in <module>
from Crypto.Cipher import AES
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\__init__.py", line 78, in <module>
from Crypto.Cipher._mode_ecb import _create_ecb_cipher
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
"""
File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

**Comment by bastimeyer** [comment]
Please take a look at already existing issues next time before submitting a new one. There's also the issue template which includes a checklist that should be followed before submitting...

I'm not going to give you a detailed answer here, because I have done this a couple of times already the past days. You are using a python version that is incompatible with your selected streamlink version. You can find all informations about this and how to fix this in the wiki. The master branch also includes changes that help preventing this.

If you don't have any questions, please close the thread. Thanks.

**Comment by sam-fletcher** [comment]
Sorry for not checking the wiki, my bad. 
I'll close it.
