### ISSUE TITLE
ImportError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by NGJimmy** [streamlink/streamlink-twitch-gui#402]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Keep getting this error when trying to launch a stream, Streamlink should be installed?

Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 12, in <module>
main()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 935, in main
handle_url()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 478, in handle_url
streams = fetch_streams_infinite(plugin, args.retry_streams)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 399, in fetch_streams_infinite
streams = fetch_streams(plugin)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 392, in fetch_streams
sorting_excludes=args.stream_sorting_excludes)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 321, in get_streams
return self.streams(*args, **kwargs)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 230, in streams
ostreams = self._get_streams()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 538, in _get_streams
return self._get_hls_streams("live")
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 502, in _get_hls_streams
force_restart=not stream_type == "live")
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 306, in parse_variant_playlist
locale = session_.localization
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 473, in localization
return Localization(self.get_option("locale"))
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 18, in __init__
self.language_code = language_code
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 38, in language_code
self.language = self.get_language(parts[0])
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 61, in get_language
return languages.get(alpha2=_language)
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 265, in get
return getattr(self, key)[value]
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 132, in __getattr__
'alpha2': self.part1,
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in __get__
val = self.f(instance)
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 198, in part1
return dict((x.part1, x) for x in self.languages if x.part1)
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in __get__
val = self.f(instance)
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 174, in languages
l, i, m, p5, p2, p1 = _fabtabular()
File "C:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 20, in _fabtabular
from pkg_resources import resource_filename
ImportError: No module named 'pkg_resources'
### Expected / Actual behavior

Stream to open?

### Reproduction steps

1. Open Twitch GUI
2. Open any stream

### Environment details (operating system, etc.)

Windows 8.1

### Comments, logs, screenshots, etc.

...

**Comment by noahleigh** [comment]
I solved this by switching the Python executable path in the Streamlink settings from the Python included in Streamlink to my main Python install with Streamlink installed via pip (gui 1.1.1, Streamlink 0.3.2)
