### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 188: ordinal not in range(128)

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#648]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
```
uname -a
Linux honeycomb 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
``` 

**Streamlink Twitch GUI version:**  
1.7.1

**Streamlink version:**  
```
/usr/local/bin/streamlink --version
streamlink 1.1.1

```

### Description

Sometimes on streams I get the following error.

Fullstack trace:

```
Found matching plugin twitch for URL twitch.tv/ronjaraumpilot
Available streams: audio_only, 160p (worst), 360p, 480p, 720p48, 900p48 (best)
Opening stream: 900p48 (hls)
Starting player: /usr/bin/vlc
Traceback (most recent call last):
File "/usr/local/bin/streamlink", line 11, in <module>
load_entry_point('streamlink==1.1.1', 'console_scripts', 'streamlink')()
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 1033, in main
handle_url()
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 594, in handle_url
handle_stream(plugin, streams, stream_name)
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 437, in handle_stream
success = output_stream_passthrough(plugin, stream)
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 262, in output_stream_passthrough
output.open()
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 24, in open
self._open()
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 219, in _open
self._open_call()
File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 234, in _open_call
log.debug(u"Calling: {0}".format(fargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 188: ordinal not in range(128)
```

### Expected / Actual behavior

Stream should start

### Reproduction steps

I haven't been able to find out how to actively reproduce this. This happens on any type of streams. Different games, different languages. (Tho I only watch EN/DE streams)
Maybe because of emotes in the stream title?

**Comment by pquerner** [comment]
I just disabled the option "Set custom title" (for player VLC) and the stream opens just fine. With that option enabled it results in the error above.

**Comment by bastimeyer** [comment]
See here:
https://github.com/streamlink/streamlink/issues/2444
