### ISSUE TITLE
How to fix streamlink install after update broke it on raspberry pi

### ISSUE THREAD

**Issue by zerger3** [streamlink/streamlink-twitch-gui#765]
Hi  i tried to update my streamlink install but it seems i fucked up. 
i used
`sudo  pip3 install --upgrade streamlink`

`pi@raspberrypi3:~/Downloads/streamlink $ streamlink 

Traceback (most recent call last):
  File "/home/pi/.local/bin/streamlink", line 6, in <module>
    from streamlink_cli.main import main
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/__init__.py", line 21, in <module>
    from .api import streams
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/session.py", line 12, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which``

can anyone help me?

**Comment by bastimeyer** [comment]
Wrong repo. This is the **Streamlink Twitch GUI** (graphical user interface), not **Streamlink**.

- https://streamlink.github.io/latest/install.html#linux-and-bsd
- https://streamlink.github.io/latest/install.html#pypi-package-and-source-code
