### ISSUE TITLE
AUR "streamlink-twitch-gui" package build error.

### ISSUE THREAD

**Issue by Sokoloft** [streamlink/streamlink-twitch-gui#944]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.2.0-1

### Streamlink version

v5.1.2-1

### Operating system, environment and configuration details

Manjaro KDE, installing through pamac gui.

### Description

The AUR package "streamlink-twitch-gui" maintained by @bastimeyer is broken. At least for this fresh install. I checked and didn't see any mentions of it. So here I am. The "streamlink-twitch-gui-bin" package built for me just fine though. Thanks.

### Debug log

```text
Preparing...
Synchronizing package databases...
Checking streamlink-twitch-gui dependencies...
Resolving dependencies...
Checking inter-conflicts...
Download of python-six (1.16.0-6) started
Download of python-isodate (0.6.1-2) started
Download of python-six (1.16.0-6) finished
Download of python-pycountry (22.3.5-1) started
Download of python-isodate (0.6.1-2) finished
Download of python-pycryptodome (3.16.0-1) started
Download of python-pycryptodome (3.16.0-1) finished
Download of python-pycountry (22.3.5-1) finished
Download of python-pysocks (1.7.1-7) started
Download of python-pysocks (1.7.1-7) finished
Download of python-lxml (4.9.2-1) started
Download of python-lxml (4.9.2-1) finished
Download of streamlink (5.1.2-1) started
Download of streamlink (5.1.2-1) finished
Download of yarn (1.22.19-1) started
Download of python-websocket-client (1.4.2-1) started
Download of python-websocket-client (1.4.2-1) finished
Download of yarn (1.22.19-1) finished
Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing python-six (1.16.0-6)...
Installing python-isodate (0.6.1-2)...
Installing python-lxml (4.9.2-1)...
Installing python-pycountry (22.3.5-1)...
Installing python-pycryptodome (3.16.0-1)...
Installing python-pysocks (1.7.1-7)...
Installing python-websocket-client (1.4.2-1)...
Installing streamlink (5.1.2-1)...
Installing yarn (1.22.19-1)...
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Refreshing PackageKit...
Cloning streamlink-twitch-gui build files...
Generating streamlink-twitch-gui information...

Building streamlink-twitch-gui...
==> Making package: streamlink-twitch-gui 2.2.0-1 (Thu 05 Jan 2023 05:01:44 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading streamlink-twitch-gui-2.2.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  620k    0  620k    0     0   629k      0 --:--:-- --:--:-- --:--:-- 1950k
  -> Downloading nwjs-0.68.1-linux64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  128M    0  335k    0     0   171k      0  0:12:46  0:00:01  0:12:45  171k
  0  128M    0  671k    0     0   242k      0  0:09:02  0:00:02  0:09:00  242k
  1  128M    1 1343k    0     0   347k      0  0:06:19  0:00:03  0:06:16  347k
  1  128M    1 2479k    0     0   531k      0  0:04:07  0:00:04  0:04:03  531k
  2  128M    2 3919k    0     0   679k      0  0:03:13  0:00:05  0:03:08  750k
  3  128M    3 4175k    0     0   644k      0  0:03:24  0:00:06  0:03:18  848k
  4  128M    4 6287k    0     0   829k      0  0:02:38  0:00:07  0:02:31 1167k
  6  128M    6 8687k    0     0  1020k      0  0:02:09  0:00:08  0:02:01 1580k
  8  128M    8 10.8M    0     0  1162k      0  0:01:53  0:00:09  0:01:44 1767k
 12  128M   12 16.2M    0     0  1470k      0  0:01:29  0:00:11  0:01:18 2296k
 12  128M   12 16.2M    0     0  1350k      0  0:01:37  0:00:12  0:01:25 2137k
 12  128M   12 16.2M    0     0  1331k      0  0:01:38  0:00:12  0:01:26 2105k
 17  128M   17 22.6M    0     0  1627k      0  0:01:20  0:00:14  0:01:06 2529k
 17  128M   17 22.9M    0     0  1619k      0  0:01:21  0:00:14  0:01:07 2495k
 32  128M   32 41.6M    0     0  2751k      0  0:00:47  0:00:15  0:00:32 6209k
 45  128M   45 58.8M    0     0  3654k      0  0:00:36  0:00:16  0:00:20 10.1M
 60  128M   60 77.4M    0     0  4534k      0  0:00:29  0:00:17  0:00:12 12.2M
 74  128M   74 96.1M    0     0  5326k      0  0:00:24  0:00:18  0:00:06 17.3M
 89  128M   89  115M    0     0  6049k      0  0:00:21  0:00:19  0:00:02 18.4M
100  128M  100  128M    0     0  6521k      0  0:00:20  0:00:20 --:--:-- 18.5M
==> Validating source files with sha256sums...
    streamlink-twitch-gui-2.2.0.tar.gz ... Passed
==> Validating source_x86_64 files with sha256sums...
    nwjs-0.68.1-linux64.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting streamlink-twitch-gui-2.2.0.tar.gz with bsdtar
==> Starting prepare()...
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "qunit@2.17.2" is incompatible with requested version "qunit@~2.6.0"
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > inject-loader@4.0.1" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "node-fetch > fetch-blob@2.1.1" has unmet peer dependency "domexception@^2.0.1".
[5/5] Building fresh packages...
Done in 14.36s.
==> Starting build()...
yarn run v1.22.19
$ /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/.bin/grunt clean:tmp_prod webpack:prod compile:linux64
Running "clean:tmp_prod" (clean) task
>> 0 paths cleaned.

Running "webpack:prod" (webpack) task
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:936:10)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:745:11)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:809:5
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Fatal error: error:0308010C:digital envelope routines::unsupported
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...

Preparing...
Cloning streamlink-twitch-gui build files...
Generating streamlink-twitch-gui information...
Checking streamlink-twitch-gui dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building streamlink-twitch-gui...
==> Making package: streamlink-twitch-gui 2.2.0-1 (Thu 05 Jan 2023 05:03:36 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found streamlink-twitch-gui-2.2.0.tar.gz
  -> Found nwjs-0.68.1-linux64.tar.gz
==> Validating source files with sha256sums...
    streamlink-twitch-gui-2.2.0.tar.gz ... Passed
==> Validating source_x86_64 files with sha256sums...
    nwjs-0.68.1-linux64.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting streamlink-twitch-gui-2.2.0.tar.gz with bsdtar
==> Starting prepare()...
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "qunit@2.17.2" is incompatible with requested version "qunit@~2.6.0"
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > inject-loader@4.0.1" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "node-fetch > fetch-blob@2.1.1" has unmet peer dependency "domexception@^2.0.1".
[5/5] Building fresh packages...
Done in 3.80s.
==> Removing existing $pkgdir/ directory...
==> Starting build()...
yarn run v1.22.19
$ /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/.bin/grunt clean:tmp_prod webpack:prod compile:linux64
Running "clean:tmp_prod" (clean) task
>> 0 paths cleaned.

Running "webpack:prod" (webpack) task
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:936:10)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:745:11)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:809:5
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Fatal error: error:0308010C:digital envelope routines::unsupported
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...

Preparing...
Cloning streamlink-twitch-gui build files...
Generating streamlink-twitch-gui information...
Checking streamlink-twitch-gui dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building streamlink-twitch-gui...
==> Making package: streamlink-twitch-gui 2.2.0-1 (Thu 05 Jan 2023 05:05:15 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found streamlink-twitch-gui-2.2.0.tar.gz
  -> Found nwjs-0.68.1-linux64.tar.gz
==> Validating source files with sha256sums...
    streamlink-twitch-gui-2.2.0.tar.gz ... Passed
==> Validating source_x86_64 files with sha256sums...
    nwjs-0.68.1-linux64.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting streamlink-twitch-gui-2.2.0.tar.gz with bsdtar
==> Starting prepare()...
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "qunit@2.17.2" is incompatible with requested version "qunit@~2.6.0"
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > inject-loader@4.0.1" has incorrect peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning "node-fetch > fetch-blob@2.1.1" has unmet peer dependency "domexception@^2.0.1".
[5/5] Building fresh packages...
Done in 3.55s.
==> Removing existing $pkgdir/ directory...
==> Starting build()...
yarn run v1.22.19
$ /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/.bin/grunt clean:tmp_prod webpack:prod compile:linux64
Running "clean:tmp_prod" (clean) task
>> 0 paths cleaned.

Running "webpack:prod" (webpack) task
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:936:10)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:745:11)
    at /var/tmp/pamac-build-sokoloft/streamlink-twitch-gui/src/streamlink-twitch-gui-2.2.0/node_modules/webpack/lib/NormalModule.js:809:5
Fatal error: error:0308010C:digital envelope routines::unsupported
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by bastimeyer** [comment]
Packaging issues do not belong here, but let me give a quick answer anyway.

> ```
> Error: error:0308010C:digital envelope routines::unsupported
>    at new Hash (node:internal/crypto/hash:71:19)
>    at Object.createHash (node:crypto:140:10)
> ```

This is caused by the `webpack==5.38.1` and `babel-loader==8.2.2` dependencies from the `v2.2.0` release. These dependencies use (cheap) `md4` hashes for local file caches when transpiling JS code, and the hashes are accelerated by Node's `crypto` module via OpenSSL. `md4` was however flagged as unsupported a while ago in OpenSSL 3 (for security reasons, but irrelevant when using for something like file cache names).

When Arch Linux finally upgraded OpenSSL from `1.1.1.q` to `3.0.7` in November 2022, all NodeJS applications trying to run those hashing algorithms started to break.

I've already bumped both dependencies in 835c21130a2c7fe437122f62e99dd89616d1fab2 and e9249cd6d5bae58fbac685bf76ad89e619122fec on 2022-11-16, and they now use different hashing algorithms for their local file caches.

----

Fixing the `streamlink-twitch-gui` PKGBUILD requires either applying those patches or adding
```sh
export NODE_OPTIONS=--openssl-legacy-provider
```
to the `build()` hook.

The environment variable can however also be set manually, as it'll be inherited by all subprocesses when building the PKGBUILD. So just run
```sh
NODE_OPTIONS=--openssl-legacy-provider makepkg -si
```
when using `makepkg`, or run this when using an AUR helper
```sh
NODE_OPTIONS=--openssl-legacy-provider $YOUR_AUR_HELPER -S streamlink-twitch-gui
```

I'll have a look at fixing the PKGBUILD of the `streamlink-twitch-gui` AUR package. `streamlink-twitch-gui-bin` and `streamlink-twitch-gui-git` are obviously not affected by this, because the former is pulling from the pre-built GitHub releases while the latter has the dependency-upgrades already applied, as it pulls the sources from the master branch.

This wouldn't have been an issue if I was able to publish a new release, but I've been waiting for NW.js bugfixes for a while now. From what it looks like though, I will have to publish a new release without NW.js bugfixes soon.

**Comment by bastimeyer** [comment]
- https://aur.archlinux.org/cgit/aur.git/commit/?h=streamlink-twitch-gui&id=97f227d1e550b5ac1517365417ac4d7a892f1a72
- https://github.com/streamlink/streamlink-twitch-gui-aur/commit/97f227d1e550b5ac1517365417ac4d7a892f1a72
